# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edwin Hung
email: edwincyhung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I study cryptocurrencies and find out how they work. I do not qualify technical details or criticize design choices. This website is a collection of posts where I can record my research and allow others to learn as well.
baseurl: "http://www.edwinhung.com" # the subpath of your site, e.g. /blog
url: "http://www.edwinhung.com" # the base hostname & protocol for your site
twitter_username: ecyhung
github_username:  edwincyhung
linkedin_username: ecyhung

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag