# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edwin Hung
email: edwincyhung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for visiting! I am a writer based in Vancouver, BC. I hope you find something interesting to read. Let me know what you're up to and I'll check it out!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.edwinhung.com" # the base hostname & protocol for your site
twitter_username: cywinr
github_username:  edwincyhung
linkedin_username: ecyhung

# Build settings
markdown: kramdown
collections:
- writing
- design
